### ISSUE TITLE
There is a plan to have an implementation of converter ?

### ISSUE THREAD

**Issue by leon-andria** [buttonwoodcx/bcx-expression-evaluator#1]

**Comment by 3cp** [comment]
I deliberately stripped value-converter and binding-behaviour support from aurelia-binding parser which I copied. The two are less relevant out of the context of aurelia HTML template. Furthermore, these are much more code need to be copied over to support those two.

You can easily implement converter as a function, put it in helper, then use inside expression as calling function.

Function should be sufficient for your use case.

Thanks for interested in our project! We really appreciate your feedback.

**Comment by leon-andria** [comment]
Thank you for your quick answer. I will use your base to integrate value converters and binding as it's required for my requirements for our framework.

**Comment by 3cp** [comment]
I think it might be easier for you to directly use aurelia paser which has all you need.

Our version added string interpolation support on top of aurelia parser. If string interpolation is not essential to you, you don't really need to develop on top of our version.
