### ISSUE TITLE
Lexer Error: Unterminated quote

### ISSUE THREAD

**Issue by francesc79** [buttonwoodcx/bcx-expression-evaluator#4]
I tried to evaluate this `'"${a+1}"'` expression but it failed with error:
Lexer Error: Unterminated quote at column 8 in expression `["${a+1}"]`

the test was:
`t.equal(evaluate('"${a+1}"', {a:1}), "${a+1}");`

In my opinion, the expression `'"${a+1}"'`  is a string and the evaluator should not evaluate it. 
If I'm right, this could be a bug.

Thanks

**Comment by 3cp** [comment]
I can reproduce it, definitely a bug.

**Comment by 3cp** [comment]
Thanks very much! Please try latest v1.0.1.

**Comment by francesc79** [comment]
works perfectly thanks so much!
